### PR TITLE
add Configuration#middleware to customize middleware stack

### PR DESCRIPTION
**Pull request by groman-me**
Added a configuration option to customize used middleware to be able to e.g. add a local cache. Here is an example of how you could initialize customized middleware list. Notice that we can pass parameters to middleware components by specifying them in an array.

``` ruby
custom_mw =
[
  [FaradayMiddleware::Caching, ActiveSupport::Cache::FileStore.new(cache_path, ... ), 
      { :ignore_params => %w[auth_token] } ],
  Faraday::Response::Logger
]

AirbrakeAPI::Client.new(:middleware => AirbrakeAPI::Configuration::DEFAULT_MIDDLEWARE + custom_mw)
```

### CODE REVIEW

**Comment by stve** [comment]
Great change! This all looks good to me. The only thing i'm hesitant about is the use of `middlewares`. Can we change to just `middleware`? Thanks.

**Comment by groman-me** [comment]
Changed!
If everything is ok now then I can squash commits.

**Comment by stve** [comment]
Looks good, thanks. Go ahead and squash it and I'll merge and release.

**Comment by groman-me** [comment]
Thank you!
Commits squashed.

**Comment by stve** [comment]
Thanks

**Pull request merged**
