### PR TITLE
Hashie dependency version changed to ~> 1.2

### PR DESCRIPTION
**Pull request by Sylvain**
All tests passed with this version.

### CODE REVIEW

**Comment by stve** [comment]
Thanks for the pull request, I will release a new version of the gem shortly.

**Comment by Sylvain** [comment]
Great news! Many thanks for the merge.

**Comment by stve** [comment]
Just released v3.2.2 with this change.  Thanks again.

**Comment by Sylvain** [comment]
Awesome! Have you any plan to release your work on the branch refactor? There is some great stuff in it! Especially the method to get the deployments.

**Comment by stve** [comment]
Yes, very soon. I want to change some of the singleton methods first but it won't be too long.

**Pull request merged**
