### PR TITLE
Update path to get the XML for a specific error

### PR DESCRIPTION
**Pull request by groman-me**
Hello!

Seems that AB has changed the URL address for a specific error. Now it's http://your_account.airbrake.io/errors/ERROR-ID.xml?auth_token=TOKEN (http://help.airbrake.io/kb/api-2/api-overview). 
It has `errors` instead of `groups`.

### CODE REVIEW

**Comment by groman-me** [comment]
Also available endpoint `http://your_account.airbrake.io/projects/PROJECT-ID/groups/ERROR-ID.xml?auth_token=TOKEN` but it is not listed in documentation. 
The current implementation returns `400 Bad Request` with body: `invalid groupId id: "....xml"`

**Comment by stve** [comment]
thanks for the tip, their documentation could use a lot of improvement

**Comment by stve** [comment]
have you found that /groups is not working for you? We actually switched the paths not too long ago from /errors to /groups so I'm not sure which path (if any) yields the correct results. see #25 for some background on that change

**Comment by groman-me** [comment]
The current implementation with /groups worked for me couple months ago. When I tried it again(about 2 weeks ago) it raised error. I've tried with old paid project and with new free account. Both have same issue. Path for notices and list of errors works ok.

**Comment by stve** [comment]
Fair enough, merged.  Thanks.

**Comment by stve** [comment]
released in version `4.5.0`, thanks!

**Pull request merged**
