### PR TITLE
Reflect update in airbrake API

### PR DESCRIPTION
**Pull request by brainopia**
Airbrake moved /errors urls to /groups

### CODE REVIEW

**Comment by stve** [comment]
Where is this change documented?  I see no mention of it in the [documentation](http://help.airbrake.io/kb/api-2/api-overview)

cc/ @airbrake

**Comment by brainopia** [comment]
Well, `#notices` has stopped working for me when I was using your gem. So I've investigating and saw that airbrake uses new url format, eg:
`https://account.airbrake.io/groups/52470453/notices/6796079237`

And if I change `groups -> errors` then it gives me error "You must supply a group".

The interesting part is although current default route is `https://account.airbrake.io/projects/ID/groups` we can replace groups with errors and it will work – seems like airbrake were trying to support old routes, but they missed one case, when you try to work with notices.

**Comment by stve** [comment]
Ok, I see the issue now.  I have a ticket open with them to fix this in their API.  Since the API endpoints have changed, I'll also make the requisite changes in AirbrakeAPI to reflect the new endpoints.  Unfortunately since your PR broke the build, I can't merge this as is.  Would you mind updating the tests to reflect the changes?  Might as well squash the commits too while you are at it.  Then I think it's good to go.  Thanks.

**Comment by brainopia** [comment]
See #26

**Pull request closed without merging**
