### PR TITLE
Changed Airbrake url to airbrake.io

### PR DESCRIPTION
**Pull request by robinroestenburg**
I received errors when accessing the api using airbrakeapp.com. Using the new airbrake.io fixed this.

### CODE REVIEW

**Comment by stve** [comment]
Can you update the tests as well as this will cause the test suite to fail.

If you are willing to point to a git repo, you might also be interested in trying the refactor I've been working on:

https://github.com/spagalloco/airbrake-api/tree/refactor

Planning to release the new version based on the refactor very soon.

**Comment by robinroestenburg** [comment]
Ah, I must admit I did not run the tests (shame on me!), will update the PR tonight.

I will try out your refactoring as well. Thanks for the work you put into this - very helpful :)

**Comment by robinroestenburg** [comment]
Tests are now working again.

**Comment by stve** [comment]
This slipped off my radar, sorry for the delay.  Released in version 3.3.0

**Pull request merged**
